# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f51ee561deb0d43f61838111c6d85b9b03e40695f696807fb6dfe2e73f876d38056c02fe1747d581b81e090348ca26ab47faac2925dc08ef337a871152d0e6a8
  conekta_private: key_yRGD32ZiscyyFziq
  conekta_public:  key_MhmRmgZkkctnCgbg

test:
  secret_key_base: dedc52398580af48a9ace05ca75709f9319f8f88f3e41390357f173533879c446c4bcd3c38ffaef43c7a3d8f0d727076c13e9a97f6b68f04bf04c8186d1da504

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
